### ISSUE TITLE
Password dialog doesn't appear anymore when trying to connect to server

### ISSUE THREAD

**Issue by DavidFichtmueller** [mimecuvalo/fireftp#117]
Since a few days again (possibly since the update to FF 35), I noticed a strange behavior when trying to connect to my servers. When a password is not saved for the account the password dialog is not shown anymore and FireFTP tries to connect without a password. (all accounts I tested this on were SFTP, some with private key, some without). If a password is stored under "Manage Accounts" the connection works as normal (but for some servers I do not like to enter the login details there). The same behavior also appears in FireSSH, so I assume it is cause by some code that is used by both addons.

Firefox 35.0
FireFTP: 2.0.22
OS: Ubuntu 14.10 and Windows 7

Has anybody else noticed this behavior?

**Comment by mimecuvalo** [comment]
There is tweaked behavior in the new version.  Users with private keys listed were asking to be able to connect with just a private key.  Do you have a private key, but you'd like to input the password each time for safety?  I might revert this change now that I think about it...

**Comment by DavidFichtmueller** [comment]
Well my SSH-Key itself requires a password. It is that password that I need to type in, and not the password for the account itself. I am not sure how it would work (previously worked) if one has a key without a password. 
But still also for the account where I don't have an SSH key and only want to log in with the password (which I don't want to save, but be prompted for each time) it will not show the dialog again.
I would greatly appreciate if the behavior would be set back to the previous version, but I guess it would also be ok, if it were to work differently to accommodate the wishes of the other users. If this means that the account settings have to be changed/updated once, that would be fine with me.
The ways I see it (correct me if I am mistaken), it all comes down to the question: does an empty password field in the account settings mean that the user wants to be prompted for a password or that there is no password to log in with?
I hope I described my situation clear enough. If not, don't hesitate to ask.
Thanks for your great addons.
Bye
  David

**Comment by alsrlw** [comment]
Yep, same here. I'd rather not save a private key passphrase, but be prompted each time. mimecuvalo, could you revert, or possibly add another option that allows to be prompted if no password/passphrase is stored?

**Comment by mimecuvalo** [comment]
This'll be reverted to the old behavior in the next FireFTP.  Thanks!

**Comment by oldunixguy** [comment]
I am running ubuntu 14.04 LTS 64bit, firefox 38.0 cannonical, FireFTP 2.0.24.1-signed.

I have the same problem with port 2222. I also don't understand how to get FireFTP to prompt me for a (non-stored) private-key passphrase. Passphrases for private key digital certificates should never be stored. My SSH server requests a user name only. So how does one configure FireFTP to use a user name (but not password) and NOT be prompted for a password but do get prompted for a Passphrase?

I successfully connect to my remote ssh server (dropbear) on port 2222 with WinSCP and Putty without a password and with a private key and passphrase.

I can't seem to get FireFTP to do so. I'm only guessing here on how to input my passphrase by placing it in the password field. (I will not continue to use FireFTP if this is the only way to enter a passphrase since this is not safe!!)  When I do this the Log window reports:
1. Connected (version 2.0, client dropbear_2014.63)
   Authentication (publickey) successful!
   Secsh channel 1 opened.
2. the status at the bottom shows "connecting... binary" and the ribbon cycles. this goes on until I close the program.
3. The Abort button is dimmed so it cannot abort this hung condition.
4. the right-hand file tree is empty.

So, it seems I cannot use this great FireFTP until these get fixed. I hope that is soon because I hate Filezilla as well (it does not securely store the keys!!!).

I can test if fixes are made available.

thanks
oldunixguy

**Comment by mimecuvalo** [comment]
Hi oldunixguy,
your comment seems off-topic to this bug report.  Perhaps you wanted comment on #126 ?
