### ISSUE TITLE
TimeStamp sync

### ISSUE THREAD

**Issue by IT-Serenity** [mimecuvalo/fireftp#148]
Seems that when a file is sent to the server, the local file is updated with the time of the file when it was uploaded.  This causes my IDE to blow up telling me that all of the scripts I uploaded have changed.

Can you not just set the file timestamp on the server of the file just pushed up to be the same as it is locally?

**Comment by mimecuvalo** [comment]
You can set this in Tools->Options->Downloads/Uploads->Keep timestamps in sync.

**Comment by opto** [comment]
is this supposed to work for upload?
Works on download. Options is set to sync timestamps (if you mean the fireftp options, what I assume).
Filezilla can set timestamp on server, so server is ok.
Problem on FF 43.0.2, firebug downloaded today.

Do you have any ideas what to do?

thanks,

Klaus

**Comment by opto** [comment]
followup to above comment:

this is what filezilla server receives after storing:
(000021)31.12.2015 22:34:39 - admin (127.0.0.1)> MDTM Changelog.txt
(000021)31.12.2015 22:34:39 - admin (127.0.0.1)> 213 20151231213439

**Comment by IT-Serenity** [comment]
I was expecting FireFTP time sync to work like FileZilla.

No matter if I am sending a file from client to server or from server to 
client...  the time stamp should be kept exactly the same.

It is as if I do not have the "Keep timestamps in sync" checked in 
Tools/Options/Downloads-Uploads.  But I do!

The thing also loses it's mind when I close it and never remembers that 
I keep date column sorted descending and I get rid of Type and Size on 
both Local And Remote Views.

And no, there is nothing set to reset settings when I close FireFox.


On 2015-12-31 15:36, opto wrote:
>
> followup to above comment:
>
> this is what filezilla server receives after storing:
> (000021)31.12.2015 22:34:39 - admin (127.0.0.1)> MDTM Changelog.txt
> (000021)31.12.2015 22:34:39 - admin (127.0.0.1)> 213 20151231213439
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mimecuvalo/fireftp/issues/148#issuecomment-168251510>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by opto** [comment]
it seems according to a new RFC the MFMT command should be used instead of MDTM which seems to be only for reading the modification time. It seems some servers implemented MDTM for both purposes contradicitng the RFC, see https://forum.filezilla-project.org/viewtopic.php?t=5697 and google search on both ftp commands.  Filezilla refused to do that as it breaks the RFC rules..

Looking at the extension code, one can find MDTM, but not MFMT.

Klaus

**Comment by Jellby** [comment]
See #43 too.

**Comment by opto** [comment]
it seems some servers do MDTM for time update, although it is not supported by the RFC.
According to texts i found on the web, that is not good in case there is a filename on the server  identical to the time string.
Others do MFMT only. Others again do nothing.

It seems fireftp requests the features of the server, so it should know whether MFTF is supported.
If yes, it should be fairly easy to send that command instead of the MDTM. The code seems pretty simple for that to add. I might do it if i need it but am totally overload now and filezilla/winscp seem to do the thing alright.

Klaus

**Comment by mimecuvalo** [comment]
Agreed that timestamp could be better.  As mentioned in #43 I'm limited on time these days and further work on this would probably have to come from some help in the community - I can guide by code reviewing.
