### ISSUE TITLE
Not working on Firefox Developer Edition

### ISSUE THREAD

**Issue by ejbogantes** [mimecuvalo/fireftp#155]
Recently the Firefox Developer Edition updated to version 44.0a2 (2015-11-04) and Fireftp is not working. It shows up but Edit button and Abort button are not showing any window and the plugin doesn't allow to create a new connection.

**Comment by LafinJack** [comment]
Same problem, the user server list is blank, the connect button is bugged out, and edit/abort do nothing.

**Comment by LafinJack** [comment]
Here's a screenshot. It's not showing in the screenshot, but my mouse cursor is hovering over where the connect button is.

https://i.imgur.com/yL5ueLH.png

**Comment by syg** [comment]
Hi, SpiderMonkey developer here.

This is probably due to backwards-incompatible changes to 'let' semantics to bring it up to date with the ES6 standard.

I see 2 uses of the now-removed let-block feature:

content/js/etc/programs.js
13:      let (str = {}) {

content/js/etc/sessionsPasswords.js
507:      let (str = {}) {

Both instances should be converted to:

{
  let str = {};
  ...
}

**Comment by LafinJack** [comment]
Thanks syg, I hope it's not to horrible a fix. :)

**Comment by vakata** [comment]
I can confirm that after fixing the lines from @syg's comment FireFTP is working normally.

**Comment by mimecuvalo** [comment]
Thanks for the feedback y'all - I'll work on fixing it in the coming week as I'm traveling currently (patches welcome in the meantime ;)

**Comment by jg-github** [comment]
vakata wrote:"I can confirm that after fixing the lines from @syg's comment FireFTP is working normally."

Is there anyway a "normal" user can test this? I'll be happy to help. 
JoeG
Berlin

**Comment by mimecuvalo** [comment]
Fixed! Thanks for all the feedback, everyone ^_^
