### ISSUE TITLE
webextension

### ISSUE THREAD

**Issue by Endor8** [mimecuvalo/fireftp#198]
Hi. How are the plans for the future? Will fireftp survive the transition to webextensions 
or will it die? I can imagine that at the moment still some needed Api's are missing.
I hope in future the will be available.

**Comment by yfdyh000** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1271553

**Comment by mstange** [comment]
And, more importantly I think, https://bugzilla.mozilla.org/show_bug.cgi?id=1247628

**Comment by mimecuvalo** [comment]
Indeed, development on FireFTP is slowing down since Firefox is dropping support for it in version 57 later in the year.  Hence, motivation for working on it isn't the highest currently. I'll probably be porting FireFTP at least to PaleMoon so that the extension survives.

The link above is the main reason: https://bugzilla.mozilla.org/show_bug.cgi?id=1247628
No sockets == no FTP :(

Going to close this and redirect you to #106

**Comment by mimecuvalo** [comment]
After 13 years and 25 million downloads later, Firefox has officially removed FireFTP and FireSSH support from the browser. Thus, I've ended support / development of the addons. I recommend switching to Waterfox to continue using the addons.
